export const TAGS = [
    "class-1",
    "class-2",
    "class-3",
    "class-4",
    "class-5",
    "class-6",
    "class-7",
    "class-8",
    "class-9",
    "class-10",
    "class-11",
    "class-12",
    "bsc",
    "bca",
    "b-tech",
    "ba",
    "bcom",
    "d.el.ed",
    "b.ed",
    "apsc",
    "adre",
    "tet",
    "ctet",
    "scert",
    "ncert",
    "computer-science",
    "english",
    "maths",
    "assamese",
    "social-science",
    "science",
    "arts",
    "physics",
    "chemistry",
    "biology",
    "zoology",
    "botany",
    "history",
    "geography",
    "politics",
    "bodo",
    "economics",
    "accountancy",
    "hindi",
    "seba",
    "ahsec",
    "asseb",
    "evs",
    "gk",
    "grammar",
    "music",
    "dance",
    "mil",
    "sanskrit",
    "elective",
    "adv-maths",
    "adv-assamese",
    "statistics",
    "biotechnology",
    "agriculture",
]

export const CATEGORY_MAP: Record<string, string> = {
  'lower-primary': 'Lower Primary (1 to 5)',
  'upper-primary': 'Upper Primary (6 to 8)',
  'secondary': 'Secondary (9 to 10)',
  'higher-secondary': 'Higher Secondary (11 to 12)',
  'ug': 'UG',
  'pg': 'PG',
  'diploma': 'Diploma',
  'teaching-course': 'Teaching Course',
  'competitive-exams': 'Competitive Exams',
  'skill-development': 'Skill Development',
  'doctorate': 'Doctorate',
  'research': 'Research',
};

export const CATEGORIES = Object.keys(CATEGORY_MAP);